server:
  port: 8084

spring:
  application:
    name: fraud
  datasource:
    username: 'ErdiSyla'
    url: jdbc:postgresql://localhost:5500/fraud
    password: 'lightweightNoReaction123'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka  